### ISSUE TITLE
auto_increment_volume_issue error on filtering for isse_type='Issue'

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1628]
**Describe the bug**
I believe this function is only used with the archive plugin but I noticed it just after this last quarterly
stack trace:
```
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ulredcarpet/janeway/src/plugins/archive_plugin/management/commands/create_archive.py", line 38, in handle
    (volume, issue) = Issue.auto_increment_volume_issue(journal)
  File "/home/ulredcarpet/janeway/src/journal/models.py", line 647, in auto_increment_volume_issue
    latest_issue = Issue.objects.filter(journal=journal, issue_type='Issue').latest('date')
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/query.py", line 787, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/query.py", line 805, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/ulredcarpet/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Issue'
```
This is the line 
`latest_issue = Issue.objects.filter(journal=journal, issue_type='Issue').latest('date')`
which I was able to get around by using an int to look up the issue_type foreign key, but pretty sure  this is not the best way of going about it. 
`latest_issue = Issue.objects.filter(journal=journal, issue_type=1).latest('date')`

**Janeway version**
a58d982

**To Reproduce**
Try to run the function in shell or use the create_archive function from the plugin
```
>>> from journal.models import Issue, Journal
>>> journal = Journal.objects.all()[0]
>>> Issue.auto_increment_volume_issue(journal)
```

**Expected behavior**
you increment the issue :)

**Screenshots**

**Additional context**
There's a lookup update on the archive plugin that needs to go in place as well. I'll be doing that

**Comment by ajrbyers** [comment]
As you say since 137 issue_type is now an FK. You can lookup the Issue type with .filter(issue_type__code='issue')
