### ISSUE TITLE
Error when loading the News homepage plugin

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2155]
**Describe the bug**
```
16:15:26 Traceback (most recent call last):
16:15:26   File "/vol/janeway/src/core/tests/test_app.py", line 269, in setUp
16:15:26     call_command('install_plugins')
16:15:26   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 131, in call_command
16:15:26     return command.execute(*args, **defaults)
16:15:26   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
16:15:26     output = self.handle(*args, **options)
16:15:26   File "/vol/janeway/src/utils/management/commands/install_plugins.py", line 52, in handle
16:15:26     plugin_settings.install()
16:15:26   File "/vol/janeway/src/core/homepage_elements/news/plugin_settings.py", line 48, in install
16:15:26     pretty='Number of Articles',
16:15:26 AttributeError: 'Setting' object has no attribute 'value'
```

**Janeway version**
2016-translation

**To Reproduce**
1. Run the test suite

**Comment by mauromsl** [comment]
Related to the above, I got this when running the upgrade script: 
```
 File "/var/www/walestest/src/core/homepage_elements/html/plugin_settings.py", line 31, in install
    models.PluginSetting.objects.get_or_create(
AttributeError: module 'utils.models' has no attribute 'PluginSetting'
```
