### ISSUE TITLE
v1.4.2.1 python manage.py install_janeway ../logs/janeway.log missing

### ISSUE THREAD

**Issue by cederom** [BirkbeckCTP/janeway#3183]
**Describe the bug**
* `python3 manage.py install_janeway` as desribed in fails with log file missing.
* Log file file location is not created by install script (needs fix).
* There is no option to select log location (feature request).

**Janeway version**
v.1.4.2.1.

**To Reproduce**
1. Follow steps from https://janeway.readthedocs.io/en/latest/installation.html#installation-guide.
2. Setup Python venv.
3. Configure `src/core/settings.py`.
4. See error presented in Screenshots section with `../logs/janeway.log` missing.

**Expected behavior**

**Screenshots**
```
$ python manage.py install_janeway
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/XXX/www/logs/janeway.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/XXX/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/XXX/venv/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/XXX/venv/lib/python3.6/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'log_file': [Errno 2] No such file or directory: '/home/XXX/www/logs/janeway.log'
```

**Desktop (please complete the following information):**
 - OS: Linux (shared hosting).
 - Browser: n/a.
 - Version: `Linux myhost 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ajrbyers** [comment]
This seems specific to the way you’ve set up logging, so not sure it’s an issue for us. Is it perhaps that the user cannot create a file on the given path?

**Comment by cederom** [comment]
1. These are my newcomer observations from first install of the platform. May be helpful to review / fix / extend existing stuff like scripts / documentation.
2. I did not setup logging myself in any custom way. This is the default setup.
3. `../logs` did not exist, was not created by the install script, not sure if I can even change this default location.
4. Creating this location by hand solves problem :-) So user is able to create files and directories there (home directory).

**Comment by ajrbyers** [comment]
Ah your right, it’s set in global settings. You can change the location but we should create the default location!

**Comment by cederom** [comment]
Thank you @ajrbyers please have mercy and patience to a new lost soul that puts faith in JaneWay :-)

I have this way of reporting issues encountered, then someone experienced can review as above, or this will be a kind of TODO list for my patches for the project :-)

Thank you :-)

**Comment by joemull** [comment]
Thanks @cederom --I'm going to add this to our version 1.5 project board: https://github.com/orgs/BirkbeckCTP/projects/16

**Comment by cederom** [comment]
AVE @mauromsl !! =)
