### ISSUE TITLE
v1.4.2.1 python manage.py install_janeway / core.0032_install_xsl_files migration encoding problem.

### ISSUE THREAD

**Issue by cederom** [BirkbeckCTP/janeway#3184]
**Describe the bug**
`python manage.py install_janeway` fails at `core.0032_install_xsl_files` migration with `UnicodeEncodeError: 'ascii' codec can't encode characters in position 528-547: ordinal not in range(128)` (see log below).

**Janeway version**
The version of Janeway under which the bug has been reproduced.
If running off of master, please, indicate the current HEAD of the Janeway installation

**To Reproduce**
1. Create database with utf8 encoding and utf8_general_ci collation.
2. `python manage.py install_janeway` .
3. See migration `core.0032_install_xsl_files` encoding problem.

**Expected behavior**
Initial setup goes smoothly with no problem :-)

**Screenshots**
```
$ python manage.py install_janeway
DEBUG 2022-10-04 15:59:45,160 include_urls P:474890 T:3916356486976 Loaded URLs for about
DEBUG 2022-10-04 15:59:45,165 include_urls P:474890 T:3916356486976 Loaded URLs for carousel
DEBUG 2022-10-04 15:59:45,166 include_urls P:474890 T:3916356486976 Loaded URLs for featured
DEBUG 2022-10-04 15:59:45,167 include_urls P:474890 T:3916356486976 Loaded URLs for html
DEBUG 2022-10-04 15:59:45,168 include_urls P:474890 T:3916356486976 Loaded URLs for issue
DEBUG 2022-10-04 15:59:45,169 include_urls P:474890 T:3916356486976 Loaded URLs for journals
DEBUG 2022-10-04 15:59:45,171 include_urls P:474890 T:3916356486976 Loaded URLs for journals_and_html
DEBUG 2022-10-04 15:59:45,172 include_urls P:474890 T:3916356486976 Loaded URLs for news
DEBUG 2022-10-04 15:59:45,174 include_urls P:474890 T:3916356486976 Loaded URLs for popular
DEBUG 2022-10-04 15:59:45,176 include_urls P:474890 T:3916356486976 Loaded URLs for preprints
DEBUG 2022-10-04 15:59:45,177 include_urls P:474890 T:3916356486976 Loaded URLs for search_bar
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, discussion, django_summernote, featured, identifiers, journal, metrics, press, production, proofing, repository, review, sessions, submission, utils
Running migrations:
  Applying core.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
(...)
  Applying core.0029_adds_default_case_for_setting_value... OK
  Applying core.0030_merge_20190405_1549... OK
  Applying core.0031_auto_20191103_2035... OK
  Applying core.0032_install_xsl_files...Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/www/new.e-health.pl/janeway/utils/management/commands/install_janeway.py", line 58, in handle
    call_command('migrate')
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/XXX/www/new.e-health.pl/janeway/core/migrations/0032_install_xsl_files.py", line 13, in install_xsl_files
    path=default_xsl_path
  File "/home/XXX/www/new.e-health.pl/janeway/core/migrations/0032_install_xsl_files.py", line 27, in install_xsl_file
    xsl_file.save()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1111, in execute_sql
    for sql, params in self.as_sql():
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in as_sql
    for obj in self.query.objs
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in <listcomp>
    for obj in self.query.objs
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1013, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/fields/files.py", line 296, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/files/storage.py", line 355, in _save
    _file.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 528-547: ordinal not in range(128)
```

**Desktop (please complete the following information):**
 - OS: Linux (shared hosting)
 - Browser: n/a.
 - Version `Linux hosting 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by cederom** [comment]
Okay, this one is caused by local user environment variables `LC_ALL` and `LC_COLLATE` setting them to any `UTF-8` (i.e. `pl_PL.UTF-8`) fixes the problem :-)

Do we want to verify that environment on setup start?
