### ISSUE TITLE
v1.4.2.1 python manage.py install_janeway / No module named 'nose'.

### ISSUE THREAD

**Issue by cederom** [BirkbeckCTP/janeway#3185]
**Describe the bug**
During `python manage.py install_janeway` missing `nose` module error occurs.

**Janeway version**
`v1.4.2.1`

**To Reproduce**
1. `python manage.py install_janeway`
2. See `nose` module missing.

**Expected behavior**
No error.

**Screenshots**
```
$ python manage.py install_janeway
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, discussion, django_summernote, featured, identifiers, journal, metrics, press, production, proofing, repository, review, sessions, submission, utils
Running migrations:
  Applying core.0001_initial... OK
(..)
  Applying journal.0053_display_article_images_settings...Parsed setting publication_fees
Parsed setting publisher_url
Parsed setting privacy_policy_url
Parsed setting publisher_name
Parsed setting copyright_notice
Parsed setting acceptance_criteria
Parsed setting collection_name
Parsed setting collection_name_plural
Parsed setting submission_checklist
Parsed setting from_address
Parsed setting replyto_address
Traceback (most recent call last):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
core.models.DoesNotExist: SettingValue matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/XXX/www/new.e-health.pl/janeway/core/templatetags/nose_tools.py", line 1, in <module>
    from nose import tools
ModuleNotFoundError: No module named 'nose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/www/new.e-health.pl/janeway/utils/management/commands/install_janeway.py", line 58, in handle
    call_command('migrate')
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/XXX/www/new.e-health.pl/janeway/journal/migrations/0053_display_article_images_settings.py", line 15, in update_setting_values
    call_command('load_default_settings')
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/www/new.e-health.pl/janeway/utils/management/commands/load_default_settings.py", line 25, in handle
    overwrite_with_defaults=options.get('force_update', False),
  File "/home/XXX/www/new.e-health.pl/janeway/utils/install.py", line 60, in update_settings
    setting=setting
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/modeltranslation/manager.py", line 370, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/modeltranslation/manager.py", line 362, in create
    return super(MultilingualQuerySet, self).create(**kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/XXX/www/new.e-health.pl/janeway/core/models.py", line 727, in save
    self.validate()
  File "/home/XXX/www/new.e-health.pl/janeway/core/models.py", line 724, in validate
    self.setting.validate(self.value)
  File "/home/XXX/www/new.e-health.pl/janeway/core/models.py", line 646, in validate
    self.group.validate(value)
  File "/home/XXX/www/new.e-health.pl/janeway/core/models.py", line 612, in validate
    validator(value)
  File "/home/XXX/www/new.e-health.pl/janeway/core/validators.py", line 54, in validate_email_setting
    template = Template(value)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/base.py", line 184, in __init__
    engine = Engine.get_default()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/engine.py", line 76, in get_default
    django_engines = [engine for engine in engines.all()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'core.templatetags.nose_tools': No module named 'nose'
```

**Desktop (please complete the following information):**
 - OS: Linux (shared hosting).
 - Browser: n/a.
 - Version `Linux hosting 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`.

**Solution**
* Module `django_nose` is missing in `requirements.txt`.
* Module `django_nose` is present in `dev_requirements.txt`.
* Module `django_nose` needs to be moved from `dev_requirements.txt` to `requirements.txt` as it is required on a production setup :-)

**Comment by joemull** [comment]
Thanks for reporting this--I think it's because of the recent addition of `src/core/templatetags/nose_tools.py`. I'll add this to the version 1.5 project board: https://github.com/orgs/BirkbeckCTP/projects/16

**Comment by cederom** [comment]
TANK U :-)
