### ISSUE TITLE
v1.4.2.1 python manage.py install_janeway / django.db.utils.IntegrityError: (1048, "Column 'group_id' cannot be null").

### ISSUE THREAD

**Issue by cederom** [BirkbeckCTP/janeway#3186]
**Describe the bug**
Error in `python manage.py install_janeway`.

**Janeway version**
`v.1.4.2.1`

**To Reproduce**
1.  `python manage.py install_janeway`.
2. See error in Logs section.

**Expected behavior**
No error :-)

**Logs**
```
$ python manage.py install_janeway
/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/jwt/utils.py:7: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, discussion, django_summernote, featured, identifiers, journal, metrics, press, production, proofing, repository, review, sessions, submission, utils
Running migrations:
(..)
  Applying journal.0053_display_article_images_settings...Parsed setting publication_fees
Parsed setting publisher_url
Parsed setting privacy_policy_url
Parsed setting publisher_name
Parsed setting copyright_notice
Parsed setting acceptance_criteria
Parsed setting collection_name
Parsed setting collection_name_plural
Parsed setting submission_checklist
Parsed setting from_address
Parsed setting replyto_address
Parsed setting editor_assignment
Parsed setting submission_acknowledgement
Parsed setting reviewer_acknowledgement
Parsed setting request_revisions
Parsed setting review_accept_acknowledgement
Parsed setting review_complete_reviewer_acknowledgement
Parsed setting review_request_sent
Parsed setting review_complete_acknowledgement
Parsed setting review_decline_acknowledgement
Parsed setting review_assignment
Parsed setting default_review_reminder
Parsed setting accepted_review_reminder
Parsed setting review_decision_accept
Parsed setting review_decision_decline
Parsed setting unassign_editor
Parsed setting subject_unassign_editor
Parsed setting review_withdrawl
Parsed setting main_contact
Parsed setting auto_signature
Parsed setting max_dois
Parsed setting enable_preprints
Parsed setting slack_logging
Parsed setting use_crossref
Parsed setting crossref_test
Parsed setting crossref_username
Parsed setting crossref_password
Parsed setting crossref_prefix
Parsed setting crossref_name
Parsed setting crossref_email
Parsed setting crossref_registrant
Parsed setting doi_display_prefix
Parsed setting doi_display_suffix
Parsed setting journal_name
Parsed setting journal_issn
Parsed setting print_issn
Parsed setting journal_theme
Parsed setting copyediting_guidelines
Parsed setting author_copyediting_guidelines
Parsed setting copyeditor_assignment_notification
Parsed setting copyeditor_notify_editor
Parsed setting copyeditor_notify_author
Parsed setting copyeditor_reopen_task
Parsed setting copyeditor_ack
Parsed setting author_copyedit_complete
Parsed setting typesetting_guide
Parsed setting production_manager_notification
Parsed setting typesetter_notification
Parsed setting typesetter_complete_notification
Parsed setting typeset_ack
Parsed setting production_complete
Parsed setting typeset_reopened
Parsed setting notify_proofing_manager
Parsed setting notify_proofreader_complete
Parsed setting notify_proofreader_assignment
Parsed setting notify_typesetter_proofing_changes
Parsed setting thank_proofreaders_and_typesetters
Parsed setting notify_editor_proofing_complete
Parsed setting notify_proofreader_cancelled
Parsed setting typesetter_corrections_complete
Parsed setting author_publication
Parsed setting proofreading_guide
Parsed setting review_steps
Parsed setting copyediting_steps
Parsed setting production_steps
Parsed setting proofing_steps
Parsed setting maintenance_mode
Parsed setting maintenance_message
Parsed setting enable_editorial_images
Parsed setting enable_editorial_display
Parsed setting display_journal_title
Parsed setting multi_page_editorial
Parsed setting password_reset
Parsed setting new_user_registration
Parsed setting draft_decisions
Parsed setting enable_save_review_progress
Parsed setting draft_message
Parsed setting draft_editor_message
Parsed setting editor_new_submission
Parsed setting limit_manuscript_types
Parsed setting section_editor_pub_notification
Parsed setting peer_reviewer_pub_notification
Parsed setting enable_one_click_access
Parsed setting enable_expanded_review_details
Parsed setting editor_digest
Parsed setting reviewer_digest
Parsed setting revision_digest
Parsed setting doi_pattern
Parsed setting is_secure
Parsed setting username
Parsed setting enable
Parsed setting password
Parsed setting editors_for_notification
Parsed setting reviewer_guidelines
Parsed setting default_review_visibility
Parsed setting default_review_days
Parsed setting production_assign_article
Parsed setting slack_webhook
Parsed setting notification_submission
Parsed setting notification_acceptance
Parsed setting journal_description
Parsed setting submission_competing_interests
Parsed setting submission_summary
Parsed setting twitter_handle
Parsed setting default_review_form
Parsed setting focus_and_scope
Parsed setting publication_cycle
Parsed setting peer_review_info
Parsed setting switch_language
Parsed setting google_analytics_code
Parsed setting use_ga_four
Parsed setting user_email_change
Parsed setting copyedit_updated
Parsed setting copyedit_deleted
Parsed setting typeset_deleted
Parsed setting notify_proofreader_edited
Parsed setting subject_author_copyedit_complete
Parsed setting subject_author_publication
Parsed setting subject_copyeditor_ack
Parsed setting subject_copyeditor_assignment_notification
Parsed setting subject_copyeditor_notify_author
Parsed setting subject_copyeditor_notify_editor
Parsed setting subject_copyeditor_reopen_task
Parsed setting subject_copyedit_deleted
Parsed setting subject_copyedit_updated
Parsed setting subject_draft_editor_message
Parsed setting subject_draft_message
Parsed setting subject_editor_assignment
Parsed setting subject_editor_digest
Parsed setting subject_editor_new_submission
Parsed setting subject_new_user_registration
Parsed setting subject_notification_acceptance
Parsed setting subject_notification_submission
Parsed setting subject_notify_editor_proofing_complete
Parsed setting subject_notify_proofing_manager
Parsed setting subject_notify_proofreader_assignment
Parsed setting subject_notify_proofreader_cancelled
Parsed setting subject_notify_proofreader_complete
Parsed setting subject_notify_proofreader_edited
Parsed setting subject_notify_typesetter_proofing_changes
Parsed setting subject_password_reset
Parsed setting subject_peer_reviewer_pub_notification
Parsed setting subject_production_assign_article
Parsed setting subject_production_complete
Parsed setting subject_production_manager_notification
Parsed setting subject_request_revisions
Parsed setting subject_reviewer_digest
Parsed setting subject_review_accept_acknowledgement
Parsed setting subject_reviewer_acknowledgement
Parsed setting subject_review_assignment
Parsed setting subject_review_complete_acknowledgement
Parsed setting subject_review_complete_reviewer_acknowledgement
Parsed setting subject_review_decision_accept
Parsed setting subject_review_decision_decline
Parsed setting subject_review_decline_acknowledgement
Parsed setting subject_review_request_sent
Parsed setting subject_review_withdrawl
Parsed setting subject_revision_digest
Parsed setting subject_section_editor_pub_notification
Parsed setting subject_submission_acknowledgement
Parsed setting subject_thank_proofreaders_and_typesetters
Parsed setting subject_typesetter_complete_notification
Parsed setting subject_typesetter_corrections_complete
Parsed setting subject_typesetter_notification
Parsed setting subject_typeset_ack
Parsed setting subject_typeset_deleted
Parsed setting subject_typeset_reopened
Parsed setting subject_user_email_change
Parsed setting disable_journal_submission
Parsed setting user_automatically_author
Parsed setting accepts_preprint_submissions
Parsed setting reviewer_form_download
Parsed setting matromo_tracking_code
Parsed setting submission_intro_text
Parsed setting abstract_required
Parsed setting subject_notify_correction_cancelled
Parsed setting notify_correction_cancelled
Parsed setting review_file_help
Parsed setting copyright_submission_label
Parsed setting max_proofreaders
Parsed setting keyword_list_page
Parsed setting suppress_how_to_cite
Parsed setting subject_accepted_review_reminder
Parsed setting subject_default_review_reminder
Parsed setting display_guest_editors
Parsed setting peer_review_upload_text
Parsed setting suppress_citations_metric
Parsed setting display_altmetric_badge
Parsed setting altmetric_badge_type
Parsed setting notify_se_draft_declined
Parsed setting subject_notify_se_draft_declined
Parsed setting enable_peer_review_data_block
Parsed setting enable_language_text
Parsed setting enable_suggested_reviewers
Parsed setting hide_review_metadata_from_authors
Parsed setting news_title
Parsed setting hide_author_email_links
Parsed setting display_login_page_notice
Parsed setting login_page_notice
Parsed setting display_register_page_notice
Parsed setting register_page_notice
Parsed setting crossref_date_suffix
Parsed setting journal_languages
Parsed setting default_journal_language
Parsed setting limit_access_to_submission
Parsed setting support_email
Parsed setting submission_access_request_text
Parsed setting revisions_complete_receipt
Parsed setting submission_access_request_contact
Parsed setting support_contact_message_for_staff
Parsed setting submission_access_request_notification
Parsed setting subject_submission_access_request_notification
Parsed setting submission_access_request_complete
Parsed setting subject_submission_access_request_complete
Parsed setting file_submission_guidelines
Parsed setting manuscript_file_submission_instructions
Parsed setting data_figure_file_submission_instructions
Parsed setting subject_revisions_complete_receipt
Parsed setting accept_article_warning
Parsed setting embargo_period
Parsed setting doi_manager_action_maximum_size
Traceback (most recent call last):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Setting matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1048, "Column 'group_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/www/new.e-health.pl/janeway/utils/management/commands/install_janeway.py", line 58, in handle
    call_command('migrate')
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/XXX/www/new.e-health.pl/janeway/journal/migrations/0053_display_article_images_settings.py", line 17, in update_setting_values
    thumb_setting, c = Setting.objects.get_or_create(name="disable_article_thumbnails")
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 509, in _create_object_from_params
    six.reraise(*exc_info)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 106, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'group_id' cannot be null")
```

**Desktop (please complete the following information):**
 - OS: Linux (shared hosting).
 - Version: `Linux hosting 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
* Some more detailed MySQL initial setup is required than explained in https://janeway.readthedocs.io/en/latest/installation.html#installation-guide ?

**Comment by cederom** [comment]
Well I have no idea on how to fix this one :-( Either MySQL setup and/or migration script error..? Help :-)

**Comment by ajrbyers** [comment]
I do! It’s not a MySQL issue but a problem with the migration not setting the group FK for a Setting.

**Comment by cederom** [comment]
How this can be fixed? :-)

**Comment by mauromsl** [comment]
Hi @cederom,

There is an inconistency on this issue report: The declared janeway version on your issue is `v1.4.2.1` however the migration you are having trouble was not part of that version (`journal.0053_display_article_images_settings`)

We've tested the installation procedure on MySQL on that version and more recent versions but your problem cannot be reproduced, so I suspect your repo was checked out onto an arbitrary commit on master.

I'm closing this but feel free to re-open if you still have the same problem from the latest release.

**Comment by cederom** [comment]
Thank you @mauromsl !! My bad !! I have recreated everything from scratch and migration works fine. Sorry!! :-)

I will now move to `v1.4.3-RC-4` maybe that will help you with some testing :-)
