### ISSUE TITLE
v1.4.3-RC-4 ./manage.py redirects missing module feedparser

### ISSUE THREAD

**Issue by cederom** [BirkbeckCTP/janeway#3200]
**Describe the bug**
* After install calling `./manager.py redirects` complains about missing `feedparser` module.
* `feedparser` module should be added to `requirements.txt`.

**Janeway version**
`v.1.4.3-RC-4`

**To Reproduce**
1. Run `./manage.py redirects` and observe error provided in the Logs section.

**Expected behavior**
`feedparser` module should be part of `requirements.txt`.

**Logs**
```
$ ./manage.py redirects
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/XXX/www/new.e-health.pl/janeway/utils/management/commands/redirects.py", line 1, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
(venv3.6janeway) [fadeaway]$ pip install feedparser
Collecting feedparser
  Downloading feedparser-6.0.10-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 2.6 MB/s
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=04ff726fac8ee514702b49799be578a852d573643eee12143314cd695e4db5c5
  Stored in directory: /home/XXX/.cache/pip/wheels/bb/cb/26/83c0b63161dc478ded6db8d83a148d32b6cce8606043c2023b
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.10 sgmllib3k-1.0.0
(venv3.6janeway) [fadeaway]$ ./manage.py redirects
/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/jwt/utils.py:7: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
DEBUG 2022-10-11 05:55:08,756 include_urls P:198084 T:3964414990144 Loaded URLs for about
DEBUG 2022-10-11 05:55:08,760 include_urls P:198084 T:3964414990144 Loaded URLs for carousel
DEBUG 2022-10-11 05:55:08,761 include_urls P:198084 T:3964414990144 Loaded URLs for featured
DEBUG 2022-10-11 05:55:08,762 include_urls P:198084 T:3964414990144 Loaded URLs for html
DEBUG 2022-10-11 05:55:08,762 include_urls P:198084 T:3964414990144 Loaded URLs for issue
DEBUG 2022-10-11 05:55:08,764 include_urls P:198084 T:3964414990144 Loaded URLs for journals
DEBUG 2022-10-11 05:55:08,766 include_urls P:198084 T:3964414990144 Loaded URLs for journals_and_html
DEBUG 2022-10-11 05:55:08,767 include_urls P:198084 T:3964414990144 Loaded URLs for news
DEBUG 2022-10-11 05:55:08,769 include_urls P:198084 T:3964414990144 Loaded URLs for popular
DEBUG 2022-10-11 05:55:08,770 include_urls P:198084 T:3964414990144 Loaded URLs for preprints
DEBUG 2022-10-11 05:55:08,771 include_urls P:198084 T:3964414990144 Loaded URLs for search_bar
```

**Server (please complete the following information):**
 - OS: Linux (shared hosting).
  - Version: `Linux hoting 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ajrbyers** [comment]
Thanks @cederom, actually I think we'll drop this as its a relic from when before Janeway was used by other peoples.
