### ISSUE TITLE
Errors when uploading PDFs created from mermaid and markdown

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/janeway#3851]
**Describe the bug**
Uploading a test PDF which was created from a mix of markdown and mermaid (i.e. contained diagrams) caused an infinite loop on a test-server. Unlikely this would be repeated live, but we should catch the error.
In document manager - uploading as manuscript, datafile and production file was fine, but uploading as proofing file caused the loop. When test server was halted and restarted, multiple copies of the file had been added.
In galleys - uploading that same file as a galley caused the same behaviour as the proofing file.

**Janeway version**
1.5.1

**To Reproduce**
Steps to reproduce the behaviour:
upload PDF created from markdown and mermaid as a proofing or galley file.

**Expected behaviour**
If such a file should not be uploaded, then an error message should indicate this.
If it should be possible to upload, then it should do so without an infinite loop, and only one copy should be uploaded.

**Additional context**
Not known whether the issue is PDF, mermaid, markdown or perhaps any file containing images?  Or how many other upload places it would fail.  Perhaps a catch for any repeated looping on an upload would be a good preventative for future unexpected files.

**Comment by ajrbyers** [comment]
@StephDriver could you upload an example file?

**Comment by StephDriver** [comment]
[SampleMermaidMarkdown.pdf](https://github.com/BirkbeckCTP/janeway/files/13818153/SampleMermaidMarkdown.pdf)

This is a one page sample file - a PDF generated from a mix of markdown and mermaid.

**Comment by joemull** [comment]
Backlog refinement: We want to make sure this is replicated with the current version of Janeway and current dev environments, so @StephDriver is going to check that it is still a problem now.

**Comment by StephDriver** [comment]
Tested above file with Master at f598a3ec

Manuscript, data/fig and Production files all fine.

Uploading as a production file threw an Programming Error.  Traceback to follow.

**Comment by StephDriver** [comment]
```
Request Method: POST
Request URL: http://localhost:8000/olh/11618/files/management/?return=/olh/review/article/11618/

Django Version: 4.2.14
Python Version: 3.12.4
Installed Applications:
['modeltranslation',
 'apps.JanewayAdminConfig',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.postgres',
 'django.contrib.contenttypes',
 'install',
 'cms',
 'core',
 'copyediting',
 'cron',
 'discussion',
 'events',
 'identifiers',
 'journal',
 'metrics',
 'comms',
 'press',
 'production',
 'proofing',
 'review',
 'repository',
 'reports',
 'security',
 'submission',
 'transform',
 'utils',
 'workflow',
 'mozilla_django_oidc',
 'django_summernote',
 'tinymce',
 'bootstrap4',
 'rest_framework',
 'foundationform',
 'materializecssform',
 'captcha',
 'simplemathcaptcha',
 'simple_history',
 'hijack',
 'hcaptcha',
 'django_bleach',
 'django.forms',
 'plugins.typesetting',
 'core.homepage_elements.search_bar',
 'core.homepage_elements.journals_and_html',
 'core.homepage_elements.html',
 'core.homepage_elements.about',
 'core.homepage_elements.carousel',
 'core.homepage_elements.journals',
 'core.homepage_elements.popular',
 'core.homepage_elements.news',
 'core.homepage_elements.issue',
 'core.homepage_elements.preprints',
 'core.homepage_elements.featured',
 'debug_toolbar']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'core.middleware.TimezoneMiddleware',
 'core.middleware.SiteSettingsMiddleware',
 'core.middleware.MaintenanceModeMiddleware',
 'cron.middleware.CronMiddleware',
 'core.middleware.CounterCookieMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'core.middleware.PressMiddleware',
 'core.middleware.GlobalRequestMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'journal.middleware.LanguageMiddleware',
 'hijack.middleware.HijackUserMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')



Traceback (most recent call last):
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (relation "core_filetext" does not exist
LINE 1: SELECT 1 AS "a" FROM "core_filetext" INNER JOIN "core_file" ...
                             ^
) was the direct cause of the following exception:
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/janeway/src/security/decorators.py", line 66, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/janeway/src/security/decorators.py", line 276, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/janeway/src/journal/views.py", line 2489, in document_management
    prod_logic.save_galley(document_article, request, file, True, label)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/janeway/src/production/logic.py", line 140, in save_galley
    article.index_full_text()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/janeway/src/submission/models.py", line 1054, in index_full_text
    if current.exists():
       ^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 154, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Janeway_Dev/venv/Janeway/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ProgrammingError at /11618/files/management/
Exception Value: relation "core_filetext" does not exist
LINE 1: SELECT 1 AS "a" FROM "core_filetext" INNER JOIN "core_file" ...
                             ^



```

**Comment by joemull** [comment]
From this stack trace I think it is erroring out when trying to do the full-text indexing. Can you say what Django settings you have around this? It would be these, either in your `core/settings.py` or core/`janeway_global_settings.py`:

```
ENABLE_FULL_TEXT_SEARCH
CORE_FILETEXT_MODEL
```

**Comment by StephDriver** [comment]
This is what I've found:

```
src/core/dev_settings.py:
  38  
  39: ENABLE_FULL_TEXT_SEARCH = True
  40  

src/core/example_settings.py:
  64  
  65: ENABLE_FULL_TEXT_SEARCH = False # Read the docs before enabling full text
  66  

src/core/janeway_global_settings.py:
  596  
  597: ENABLE_FULL_TEXT_SEARCH = False
  598  

docs/source/dev/configuration.rst:
   94  
   95: ``CORE_FILETEXT_MODEL = "core.PGFileText"``
   96  

  101  .. warning::
  102:     If you intend to use the ``PGFileText`` model, you must set the ``CORE_FILETEXT_MODEL`` setting before you install Janeway and/or before you
  103      upgrade an installation to v1.4.2. Otherwise, the migration engine will install the regular ``core.FileText`` model instead.

src/core/example_settings.py:
  67  # Model used for indexing full text files
  68: CORE_FILETEXT_MODEL = "core.FileText"  # Use "core.PGFileText" for Postgres

**Comment by joemull** [comment]
@StephDriver OK that helps, but you probably also have a `src/core/settings.py` in there, which will override `janeway_global_settings.py`, but it is Git-ignored, so by default it does not show up in IDE search results. That's the key one. Can you look that up and find any full-text search settings in there?

**Comment by ajrbyers** [comment]
Tested this as Steph did above and cannot replicate this issue.

I also tested this on Prod and had no issues.
