### ISSUE TITLE
Duplicate roles causes error when adding a new account

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/janeway#4286]
This may just be a dev error, but here goes:

- I was adding a new article via the submissions, using a superuser account and putting in a new/unknown author as the author rather than 'myself'. And I received the following error on submitting the third form in the process (not added the article itself yet).
- [journal]/submit/13/authors/

### Error Message

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">MultipleObjectsReturned at /submit/12/authors/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">get() returned more than one Role -- it returned 2!</pre>
Request Method: | POST
-- | --
http://localhost:8000/alpha/submit/12/authors/
4.2.11
MultipleObjectsReturned
get() returned more than one Role -- it returned 2!
/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/db/models/query.py, line 640, in get
submission.decorators.submission_is_enabled_wrapper
/Users/stephdriver/Documents/Janeway/venv/Janeway/bin/python3
3.9.19
['/Users/stephdriver/Documents/Janeway/janeway/src',  '/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',  '/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9',  '/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',  '/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages',  '/Users/stephdriver/Documents/Janeway/janeway/src/plugins']
Thu, 20 Jun 2024 08:41:29 +0100

### details
https://dpaste.com/F2N2BXV9K

**Comment by StephDriver** [comment]
Traceback (most recent call last):
  File "/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/submission/decorators.py", line 33, in submission_is_enabled_wrapper
    return func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/security/decorators.py", line 1371, in _article_is_not_submitted
    return func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/security/decorators.py", line 728, in wrapper
    return func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/security/decorators.py", line 66, in wrapper
    return func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/security/decorators.py", line 1329, in submission_authorised_wrapper
    return func(request, *args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/submission/views.py", line 288, in submit_authors
    logic.add_user_as_author(author, article)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/submission/logic.py", line 48, in add_user_as_author
    user.add_account_role("author", article.journal)
  File "/Users/stephdriver/Documents/Janeway/janeway/src/core/models.py", line 415, in add_account_role
    role = Role.objects.get(slug=role_slug)
  File "/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/stephdriver/Documents/Janeway/venv/Janeway/lib/python3.9/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /submit/12/authors/
Exception Value: get() returned more than one Role -- it returned 2!

**Comment by StephDriver** [comment]
Also happening when I add self as author - so may not be about author choice.  Triggered on add self button press.

**Comment by ajrbyers** [comment]
In admin, check if you have duplicate Role values for the journal you're loading an article for. We need to add a catch for this though so keep the ticket open.

**Comment by StephDriver** [comment]
> In admin, check if you have duplicate Role values for the journal you're loading an article for. 

Account I was using has multiple roles (editor, reviewer etc) in that journal, but only has each of them once.  No duplicates.

**Comment by joemull** [comment]
@S-Haime Haha no worries--it is a fair question! For this one, I don't think the new author system changed anything.

Andy's right that it's about the `Role` object being duplicated in the database somehow, and the `Account.add_account_role` function not accounting for the case where there are two. I think we just need to make sure it's not possible to create two `Role` objects with the same `slug`. Here's my proposed solution for BRF:

## Proposed solution

- [ ] Add a unique constraint to `Role.slug`.
- [ ] Add a data migration to merge any duplicates.
