### ISSUE TITLE
Install: django.db.utils.OperationalError: (1060, "Duplicate column name 'folder_name'")

### ISSUE THREAD

**Issue by seonghobae** [BirkbeckCTP/janeway#451]
```
(janeway) root@b2:~/janeway/src# python3 manage.py install_janeway
No changes detected in app 'sites'
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, django_summernote, featured, identifiers, journal, metrics, preprint, press, production, proofing, review, sessions, sites, submission, utils
Running migrations:
  Applying core.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying journal.0001_initial... OK
  Applying submission.0001_initial... OK
  Applying carousel.0001_initial... OK
  Applying carousel.0002_auto_20170711_1203... OK
  Applying cms.0001_initial... OK
  Applying comms.0001_initial... OK
  Applying comms.0002_auto_20170816_1050... OK
  Applying copyediting.0001_initial... OK
  Applying copyediting.0002_auto_20170711_1203... OK
  Applying copyediting.0003_auto_20180122_2211... OK
  Applying copyediting.0004_auto_20180412_1544... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying submission.0002_auto_20170813_1302... OK
  Applying submission.0003_field... OK
  Applying submission.0004_fieldanswer... OK
  Applying submission.0005_field_width... OK
  Applying journal.0002_auto_20170711_1203... OK
  Applying journal.0003_pinnedarticle... OK
  Applying journal.0004_auto_20170813_1302... OK
  Applying submission.0006_field_journal... OK
  Applying submission.0007_auto_20170822_1256... OK
  Applying submission.0008_auto_20170907_1652... OK
  Applying submission.0008_auto_20170907_1159... OK
  Applying submission.0009_merge_20170907_1721... OK
  Applying submission.0010_auto_20170915_1146... OK
  Applying submission.0011_auto_20170921_0937... OK
  Applying submission.0012_auto_20170929_0835... OK
  Applying submission.0013_auto_20171004_1002... OK
  Applying submission.0014_auto_20171009_1028... OK
  Applying submission.0015_auto_20171013_1104... OK
  Applying press.0001_initial... OK
  Applying press.0002_auto_20170813_1302... OK
  Applying press.0003_auto_20170829_1501... OK
  Applying press.0002_auto_20170727_1504... OK
  Applying press.0004_merge_20170908_1215... OK
  Applying press.0005_auto_20170929_0834... OK
  Applying press.0006_press_preprints_about... OK
  Applying press.0007_auto_20171004_1605... OK
  Applying press.0008_auto_20171005_1158... OK
  Applying press.0009_press_preprint_editors... OK
  Applying press.0010_presssetting... OK
  Applying press.0011_remove_press_preprint_editors... OK
  Applying press.0012_presssetting_is_boolean... OK
  Applying submission.0016_auto_20171106_0909... OK
  Applying submission.0017_auto_20171114_1502... OK
  Applying submission.0018_article_preprint_journal_article... OK
  Applying submission.0019_auto_20171130_1115... OK
  Applying core.0002_auto_20170711_1203... OK
  Applying core.0003_load_countries... OK
  Applying core.0004_auto_20170813_1302... OK
  Applying core.0005_auto_20170816_0851... OK
  Applying core.0006_auto_20170816_0900... OK
  Applying core.0007_auto_20170829_1501... OK
  Applying core.0008_auto_20170925_1129... OK
  Applying core.0009_auto_20170925_1133... OK
  Applying core.0010_account_enable_public_profile... OK
  Applying core.0011_auto_20171010_1535... OK
  Applying core.0012_workflowlog... OK
  Applying core.0013_auto_20180207_1525... OK
  Applying core.0014_auto_20180408_0729... OK
  Applying core.0015_supplementaryfile... OK
  Applying core.0014_workflowelement_jump_url... OK
  Applying core.0016_merge_20180417_1131... OK
  Applying core.0017_auto_20180417_1254... OK
  Applying cron.0001_initial... OK
  Applying cron.0002_auto_20170711_1203... OK
  Applying cron.0003_auto_20171121_1115... OK
  Applying django_summernote.0001_initial... OK
  Applying featured.0001_initial... OK
  Applying featured.0002_auto_20170711_1203... OK
  Applying identifiers.0001_initial... OK
  Applying identifiers.0002_auto_20170711_1203... OK
  Applying identifiers.0003_brokendoi_journal... OK
  Applying identifiers.0004_auto_20170921_1113... OK
  Applying journal.0005_auto_20171002_1503... OK
  Applying journal.0006_auto_20171115_1216... OK
  Applying journal.0007_auto_20180129_2342... OK
  Applying journal.0008_auto_20180129_2352... OK
  Applying journal.0007_auto_20180208_1225... OK
  Applying journal.0009_merge_20180208_1443... OK
  Applying journal.0010_auto_20180412_1544... OK
  Applying metrics.0001_initial... OK
  Applying metrics.0002_altmetric... OK
  Applying metrics.0003_auto_20170921_0937... OK
  Applying metrics.0004_auto_20180308_1732... OK
  Applying preprint.0001_initial... OK
  Applying preprint.0002_auto_20171009_1134... OK
  Applying preprint.0003_auto_20171009_1206... OK
  Applying preprint.0004_comment_date_time... OK
  Applying preprint.0005_auto_20171010_1132... OK
  Applying preprint.0006_preprintversion_date_time... OK
  Applying preprint.0007_auto_20171013_1104... OK
  Applying preprint.0008_auto_20171013_1104... OK
  Applying preprint.0009_subject_enabled... OK
  Applying preprint.0010_versionqueue... OK
  Applying preprint.0011_auto_20171130_1507... OK
  Applying press.0013_press_preprint_decline... OK
  Applying press.0014_auto_20171127_1502... OK
  Applying press.0015_press_tracking_code... OK
  Applying press.0015_auto_20180208_1442... OK
  Applying press.0016_merge_20180319_1139... OK
  Applying production.0001_initial... OK
  Applying proofing.0001_initial... OK
  Applying proofing.0002_proofingtask_proofed_files... OK
  Applying proofing.0003_typesetterproofingtask_files... OK
  Applying review.0001_initial... OK
  Applying review.0002_reviewformelement_default_visibility... OK
  Applying review.0003_auto_20180208_1225... OK
  Applying sessions.0001_initial... OK
  Applying sites.0003_auto_20180527_0530...Traceback (most recent call last):
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1060, "Duplicate column name 'folder_name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/janeway/src/utils/management/commands/install_janeway.py", line 26, in handle
    call_command('migrate')
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 87, in database_forwards
    field,
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/mysql/schema.py", line 48, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 429, in add_field
    self.execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/root/.virtualenvs/janeway/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1060, "Duplicate column name 'folder_name'")
(janeway) root@b2:~/janeway/src#
```

**Comment by ajrbyers** [comment]
A quick workaround for this is to run `python3 manage.py migrate sites --fake`

I'll look into the larger issue later.

**Comment by ajrbyers** [comment]
A clean instal_janeway command doesn't result in this error anymore. Closing.
