### ISSUE TITLE
Reporting Errors Deploying Janeway on Reclaim Hosting

### ISSUE THREAD

**Issue by chrisdaaz** [BirkbeckCTP/janeway#512]
I'm following the instructions on [deploying Janeway on Reclaim Hosting](https://github.com/BirkbeckCTP/janeway/wiki/Deploying-Janeway-on-Reclaim-Hosting) and I'm seeing some errors that seem to prevent success with this. 

**Question about step 6**
Am I supposed to modify this line `/home/janewayuser/jw/src/core/wsgi.py` or enter it as is?

**On step 9**
Everything works great until I get to this task:
```
  building '_mysql' extension
  creating build/temp.linux-x86_64-3.5
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPI
C -Dversion_info=(1,3,13,'final',0) -D__version__=1.3.13 -I/opt/alt/python35/include/python3.5m -c _mysql.c -o build/temp.linux-x86_64-3.5/_mysql.o
  _mysql.c:29:19: fatal error: mysql.h: No such file or directory
   #include "mysql.h"
                     ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mysqlclient
```
and it seems to retry here:

```
    building '_mysql' extension
    creating build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -f
PIC -Dversion_info=(1,3,13,'final',0) -D__version__=1.3.13 -I/opt/alt/python35/include/python3.5m -c _mysql.c -o build/temp.linux-x86_64-3.5/_mysql.o
    _mysql.c:29:19: fatal error: mysql.h: No such file or directory
     #include "mysql.h"
                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/nulibrec/virtualenv/janeway_src/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hihdqmka/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file
__, 'exec'))" install --record /tmp/pip-pv97zank-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/nulibrec/virtualenv/janeway_src/3.5/include/site/python3.5/mysqlclient" failed with error code 1 in /tmp/pip-build-hihdqmka/my
sqlclient/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**On step 16**
I get this traceback:
```
$ python3 manage.py install_janeway
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib/python3.5/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/home/nulibrec/virtualenv/janeway_src/3.5/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 943, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 943, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'raven'
```

**Step 18**
I don't know what "install page" is being referred to, and my guess is that it's probably due to errors running `manage.py install_janeway`.

If you have any guidance or advice on troubleshooting these errors, please let me know. I'd be happy to volunteer time toward documentation or QA testing efforts to contribute to this project!

**Comment by ajrbyers** [comment]
Hey Chris,

Could you let me know what server youre reclaim account is on? I suspect that not all of them are setup to support Janeway yet based on this error. 

Andy

**Comment by chrisdaaz** [comment]
It's `fugazi.reclaimhosting.com`

**Comment by ajrbyers** [comment]
As far as I know Kraftwerk is the only server that is 100% setup for Janeway. The team at reclaim did say they would extend support to other servers so there are a couple of options open to you:

1. Open a support ticket and ask to be moved to Kraftwerk
2. Open a support ticket and ask if they can install Janeways dependencies in Fugazi

Let me know if we can help more. I’m free tomorrow and Wednesday for a chat/call to help out if you need it.

**Comment by chrisdaaz** [comment]
Thanks @ajrbyers ! I opened a ticket with Reclaim.
