### ISSUE TITLE
Importer fails to scrape some UP articles

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#585]
master @ 494a010b1509ee45685193fe24443e398c118f67

```
Traceback (most recent call last):
  File "src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/vol/janeway/src/utils/management/commands/scrape_oai.py", line 35, in handle
    importer.import_oai(**options)
  File "/vol/janeway/src/utils/importer.py", line 121, in import_oai
    parse_OAI(journal, options, user)
  File "/vol/janeway/src/utils/importer.py", line 143, in parse_OAI
    up.import_oai(journal, user, soup, domain)
  File "/vol/janeway/src/utils/importers/up.py", line 180, in import_oai
    import_article(journal, user, identifier.contents[0], thumb_path)
  File "/vol/janeway/src/utils/importers/up.py", line 128, in import_article
    article_id = matches.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ajrbyers** [comment]
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment]
@mauromsl updates to the importer fixed this?

**Comment by mauromsl** [comment]
yep, sorted
