### ISSUE TITLE
Docker DB Folder

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#624]
If the DB folder doesn't exist when `make install` is run:

```
ajrbyers@starfall:~/janeway$ make install
touch db/janeway.sqlite
touch: cannot touch 'db/janeway.sqlite': No such file or directory
Makefile:44: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by ajrbyers** [comment]
Further, the postgres-data folder seems to have bad permissions:

```
ajrbyers@starfall:~/janeway$ make install
touch db/janeway.sqlite
bash -c "make command CMD=install_janeway"
make[1]: Entering directory '/home/ajrbyers/janeway'
bash -c "make janeway entrypoint=\"src/manage.py install_janeway\""
make[2]: Entering directory '/home/ajrbyers/janeway'
docker-compose run  --rm --service-ports janeway-web src/manage.py install_janeway
Starting janeway_janeway-postgres_1_735c3b8f02a3 ... done
Starting janeway_start_dependencies_1_340316cbc72c ... done
Building janeway-web
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 873, in run
    self.toplevel_options, self.project_dir
  File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 1328, in run_one_off_container
    **container_options)
  File "/usr/local/lib/python3.6/dist-packages/compose/service.py", line 320, in create_container
    self.ensure_image_exists()
  File "/usr/local/lib/python3.6/dist-packages/compose/service.py", line 356, in ensure_image_exists
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/compose/service.py", line 1080, in build
    platform=self.platform,
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/api/build.py", line 154, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/utils/build.py", line 30, in tar
    files=sorted(exclude_paths(root, exclude, dockerfile=dockerfile[0])),
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/utils/build.py", line 49, in exclude_paths
    return set(pm.walk(root))
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/home/ajrbyers/.local/lib/python3.6/site-packages/docker/utils/build.py", line 184, in rec_walk
    for f in os.listdir(current_dir):
PermissionError: [Errno 13] Permission denied: '/home/ajrbyers/janeway/db/postgres-data'
Makefile:40: recipe for target 'janeway' failed
make[2]: *** [janeway] Error 1
make[2]: Leaving directory '/home/ajrbyers/janeway'
Makefile:42: recipe for target 'command' failed
make[1]: *** [command] Error 2
make[1]: Leaving directory '/home/ajrbyers/janeway'
Makefile:44: recipe for target 'install' failed
make: *** [install] Error 2
ajrbyers@starfall:~/janeway$ cd db/
ajrbyers@starfall:~/janeway/db$ ls
janeway.sqlite  postgres-data
ajrbyers@starfall:~/janeway/db$ ls -al
total 12
drwxrwxr-x  3 ajrbyers ajrbyers 4096 Nov 17 21:11 .
drwxrwxr-x  7 ajrbyers ajrbyers 4096 Nov 17 21:10 ..
-rw-rw-r--  1 ajrbyers ajrbyers    0 Nov 17 21:11 janeway.sqlite
drwx------ 19      999 root     4096 Nov 17 21:11 postgres-data

```

**Comment by ajrbyers** [comment]
Second issue is fixed with `chown -R user:user` but shouldn't be needed.

**Comment by mauromsl** [comment]
Can you add the result of  `pip freeze | grep docker` and `docker-compose -v`?
The first issue is a bug. The second is not due to bad permissions (The user in the mysql container doesn't exist in your host, hence why its 999:root), but rather due to your docker-compose failing to mount a volume over which you have no permission on the host, which I've never seen before.

**Comment by ajrbyers** [comment]
Odd. It was a totally clean install of Elementary (Ubuntu 18.04)

**Comment by mauromsl** [comment]
just add the result of `pip freeze | grep docker`,  `docker-compose -v` and `docker -v` so I can test with your setup.

**Comment by ajrbyers** [comment]
Roger that. Will be working this evening so will add it then. Currently on phone. Workaround was to swap to SQLite :p
