### ISSUE TITLE
AnonymousUser's denied access can't be logged and raises a 500

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#793]
On the demo journal:

```janeway-web_1         | ERROR 2019-01-24 16:23:46,359 exception P:9 T:140406818576128 Internal Server Error: /demo/article/id/2/
janeway-web_1         | Traceback (most recent call last):
janeway-web_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
janeway-web_1         |     response = get_response(request)
janeway-web_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
janeway-web_1         |     response = self._get_response(request)
janeway-web_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
janeway-web_1         |     response = self.process_exception_by_middleware(e, request)
janeway-web_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
janeway-web_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
janeway-web_1         |   File "/vol/janeway/src/security/decorators.py", line 637, in wrapper
janeway-web_1         |     return func(request, *args, **kwargs)
janeway-web_1         |   File "/vol/janeway/src/security/decorators.py", line 432, in wrapper
janeway-web_1         |     deny_access(request)
janeway-web_1         |   File "/vol/janeway/src/security/decorators.py", line 941, in deny_access
janeway-web_1         |     "".format(request=request))
janeway-web_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 239, in inner
janeway-web_1         |     return func(self._wrapped, *args)
janeway-web_1         | AttributeError: 'AnonymousUser' object has no attribute 'email'```

**Comment by ajrbyers** [comment]
Denied by is_accepted() returning false or the article_object being None...

**Comment by mauromsl** [comment]
I believe the article object was None at that point somehow, as I was getting a permission error on my Authenticated User
`INFO 2019-01-24 16:24:50,961 decorators P:9 T:140406818576128 [ACCESS_DENIED:mauro.***@****.com:/article/id/2/]`
